### ISSUE TITLE
[question]: Why are you using one statefulset per instance

### ISSUE THREAD

**Issue by landorg** [Ontotext-AD/graphdb-helm#12]
Shouldn't we use the statefulset as intended with multiple replicas instead of having multiple statefulsets one for each replica?
Can you please explain what is the reason behind that?

Having a statefulset for all the workers and one for the masters would have some nice advantages like:
* being able to set an [update strategy](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies)
* using kubectl rollout restart ..

**Comment by nikolaykolev** [comment]
There are a few difficulties that we haven't found good solutions yet. The problems that we'll face if we use "real" statefulsets are:
- Linking and unlinking masters/workers on auto scaling up/down
- iterating over replicas for different properties, provisioning
- Handle per master/worker properties 

We do plan to do it, but until we find the proper way we'll stick to this method

**Comment by landorg** [comment]
I see. Thanks for clarification

**Comment by Sukhumi** [comment]
With the release of the helm chart for GraphDB 10 we are no longer using one statefulset per instance and the issue is no longer valid.
