### ISSUE TITLE
Wrong file path configuration for the loadrdf tool

### ISSUE THREAD

**Issue by boboetuk** [Ontotext-AD/graphdb-helm#20]
The file path for the input of loadrdf tool points to the preload tool 

 /opt/graphdb/dist/bin/loadrdf {{ $.Values.graphdb.tools.loadrdf.flags }} -c /tmp/graphdb/config.ttl -m parallel /tmp/graphdb/{{$.Values.graphdb.tools.**preload**.rdfDataFile}}

**Comment by nikolaykolev** [comment]
Fixed, thx
