### ISSUE TITLE
Allow specifying resource requests/limits for all containers

### ISSUE THREAD

**Issue by sjentzsch** [Ontotext-AD/graphdb-helm#64]
Due to company policies we need to be able to specify resource requests & limits for all containers of the graphdb Helm chart deployment. Currently, this is not possible.

I would file a MR to implement it, and will reference this issue doing so.

**Comment by QcFe** [comment]
Got the same issue here, is there any update on this?

**Comment by sjentzsch** [comment]
Work is done, waiting for s/o to approve & merge it in ... @nikolaykolev you released `[10.2.3](https://github.com/Ontotext-AD/graphdb-helm/releases/tag/10.2.3)` yesterday, how about giving this a quick review? :-)

**Comment by sjentzsch** [comment]
CC @Sukhumi @mihailradkov anyone?
